### PR TITLE
Fix: Already borrowed: BorrowMutError. Don't borrow_mut() recursively

### LINKED ISSUE #31: Allow inner calls
See https://github.com/paritytech/parity-ethereum/issues/9276#issuecomment-411187169

### PR DESCRIPTION
**Pull request by fckt**
fixes #31 
To do: add a test

### CODE REVIEW

File: src/external.rs [hunk 1]
```diff
@@ -1,6 +1,7 @@
 use std::any::Any;
 use std::collections::HashMap;
 use std::rc::Rc;
+use std::cell::{RefCell};
```
Comment (NikVolf) [inline src/external.rs]: Redundant braces

**Comment by fckt** [comment]
> How about make an example which utilizes fix?

https://github.com/paritytech/pwasm-test/pull/32/files#diff-ac1fb4b8a2e77353fde52407b8606587R40
